#!/bin/bash
# Migration Script: Update submodules to use reusable workflows
# This script creates simplified CI workflows that call the reusable ones from conxian-business

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKFLOWS_DIR="$REPO_ROOT/.github/workflows/reusable"

echo "=============================================="
echo "Migrating Submodules to Reusable Workflows"
echo "=============================================="
echo ""

# Define migration templates for each repo type
create_rust_ci() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    
    cat > "$repo_path/.github/workflows/ci.yml" << 'EOF'
# Simplified Rust CI - calls reusable workflows from conxian-business
# Generated by migration script

name: CI

on:
  push:
    branches: [main, staged, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, staged, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Rust CI
    uses: Conxian/conxian-business/.github/workflows/reusable/rust-ci.yml@main
    with:
      rust_version: "1.96.0"

  dependency-review:
    name: Dependency Review
    uses: Conxian/conxian-business/.github/workflows/reusable/dependency-review.yml@main

  secret-scan:
    name: Secret Scan
    uses: Conxian/conxian-business/.github/workflows/reusable/secret-scan.yml@main
EOF
    
    echo "✅ Created CI for $repo_name"
}

create_node_ci() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    
    cat > "$repo_path/.github/workflows/ci.yml" << 'EOF'
# Simplified Node.js CI - calls reusable workflows from conxian-business
# Generated by migration script

name: CI

on:
  push:
    branches: [main, staged, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, staged, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Node.js CI
    uses: Conxian/conxian-business/.github/workflows/reusable/node-ci.yml@main
    with:
      node_version: "20"
      pnpm_version: "10"

  codeql:
    name: CodeQL
    uses: Conxian/conxian-business/.github/workflows/reusable/codeql.yml@main
    with:
      languages: typescript

  dependency-review:
    name: Dependency Review
    uses: Conxian/conxian-business/.github/workflows/reusable/dependency-review.yml@main

  secret-scan:
    name: Secret Scan
    uses: Conxian/conxian-business/.github/workflows/reusable/secret-scan.yml@main
EOF
    
    echo "✅ Created CI for $repo_name"
}

create_clarity_ci() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    
    cat > "$repo_path/.github/workflows/ci.yml" << 'EOF'
# Simplified Clarity/Blockchain CI
# Generated by migration script

name: CI

on:
  push:
    branches: [main, staged, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, staged, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hygiene:
    name: Hygiene
    uses: Conxian/conxian-business/.github/workflows/reusable/hygiene.yml@main

  node-ci:
    name: Node.js CI
    uses: Conxian/conxian-business/.github/workflows/reusable/node-ci.yml@main
    with:
      node_version: "20"
      pnpm_version: "10"

  clarity:
    name: Clarinet Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Clarinet
        uses:docker://hirosystems/clarinet:latest
        with:
          args: check --manifest-path Clarinet.toml

  codeql:
    name: CodeQL
    uses: Conxian/conxian-business/.github/workflows/reusable/codeql.yml@main
    with:
      languages: typescript

  dependency-review:
    name: Dependency Review
    uses: Conxian/conxian-business/.github/workflows/reusable/dependency-review.yml@main

  secret-scan:
    name: Secret Scan
    uses: Conxian/conxian-business/.github/workflows/reusable/secret-scan.yml@main
EOF
    
    echo "✅ Created CI for $repo_name (with Clarity)"
}

# ============================================
# MIGRATION
# ============================================

echo "Checking which repos to migrate..."
echo ""

# conxian-nexus (Rust)
if [ -f "$REPO_ROOT/conxian-nexus/Cargo.toml" ]; then
    create_rust_ci "$REPO_ROOT/conxian-nexus"
fi

# conxius-enclave-sdk (Rust)
if [ -f "$REPO_ROOT/conxius-enclave-sdk/Cargo.toml" ]; then
    create_rust_ci "$REPO_ROOT/conxius-enclave-sdk"
fi

# lib-conxian-core (Rust)
if [ -f "$REPO_ROOT/lib-conxian-core/Cargo.toml" ]; then
    create_rust_ci "$REPO_ROOT/lib-conxian-core"
fi

# conxian-gateway (Mixed - has both Rust and Node)
if [ -f "$REPO_ROOT/conxian-gateway/package.json" ]; then
    create_node_ci "$REPO_ROOT/conxian-gateway"
fi

# conxius-wallet (Node + blockchain)
if [ -f "$REPO_ROOT/conxius-wallet/package.json" ]; then
    create_node_ci "$REPO_ROOT/conxius-wallet"
fi

# conxian-ui (Node)
if [ -f "$REPO_ROOT/conxian-ui/package.json" ]; then
    create_node_ci "$REPO_ROOT/conxian-ui"
fi

# conxius-platform (Node)
if [ -f "$REPO_ROOT/conxius-platform/package.json" ]; then
    create_node_ci "$REPO_ROOT/conxius-platform"
fi

# conxian-labs-site (Node)
if [ -f "$REPO_ROOT/conxian-labs-site/package.json" ]; then
    create_node_ci "$REPO_ROOT/conxian-labs-site"
fi

# conxius-orbit (Node + Clarity)
if [ -f "$REPO_ROOT/conxius-orbit/Clarinet.toml" ]; then
    create_clarity_ci "$REPO_ROOT/conxius-orbit"
elif [ -f "$REPO_ROOT/conxius-orbit/package.json" ]; then
    create_node_ci "$REPO_ROOT/conxius-orbit"
fi

echo ""
echo "=============================================="
echo "✅ Migration Complete!"
echo "=============================================="
echo ""
echo "Next steps:"
echo "1. Review the generated .github/workflows/ci.yml files"
echo "2. Run: git add . && git commit -m 'chore: adopt reusable CI workflows'"
echo "3. Push to a branch and create PRs for each submodule"
echo ""
echo "Note: The reusable workflows are called with @main ref."
echo "      You may want to pin to a specific version tag for stability."
