-- This repository is public.
--
-- Internal database schemas, operational thresholds, and treasury telemetry models
-- are maintained in the Conxian Linear workspace.
--
-- See:
-- - https://linear.app/conxian-labs
-- - https://linear.app/conxian-labs/issue/CON-256
